stages:
  - build
  - deploy

# Build Stage
build:
  stage: build
  tags: 
    - general-shell
  script:
    # Build Docker image 
    - docker build -t $CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME-front-end:$CI_COMMIT_REF_NAME .
    - echo "Build Successful and container created"

# Deploy Stage
deploy:
  stage: deploy
  script:
   
    # Define container name
    - CONTAINER_NAME="$CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME-front-end"

    # Remove any existing container with the same name (force removal if running)
    - docker ps -a -q --filter "name=$CONTAINER_NAME" | xargs -r docker rm -f

    # Run the new container with the specified container name and exposed port
    - docker run -d --name $CONTAINER_NAME -p 80:80 $CI_PROJECT_NAMESPACE-$CI_PROJECT_NAME-front-end:$CI_COMMIT_REF_NAME

    # Deploy to a server 
    - docker ps
  only:
    - main  # Trigger deploy only when changes are pushed to the main branch
