stages:
  - build
  - deploy

# Build Stage
build:
  stage: build
  image: docker:latest
  script:
    # 
    # Build Docker image 
    - docker build -t 192.168.192.25:1234/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/front-end:$CI_COMMIT_REF_NAME .
    - echo "Build Successful"

# Deploy Stage
deploy:
  stage: deploy
  script:
    # Login to the self-hosted GitLab Container Registry
    - echo $CI_JOB_TOKEN | docker login -u $CI_REGISTRY_USER --password-stdin 192.168.192.25:1234
    # Push the Docker image to the self-hosted GitLab Container Registry
    - docker push 192.168.192.25:1234/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/front-end:$CI_COMMIT_REF_NAME

    # Deploy to a server 
    - echo "Container Created"
    #- ssh gitlab-runner@192.168.192.25 "docker pull 192.168.192.25:1234/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/my-react-app-image:$CI_COMMIT_REF_NAME && docker run -d -p 80:80 192.168.192.25:1234/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME/my-react-app-image:$CI_COMMIT_REF_NAME"
  only:
    - main  # Trigger deploy only when changes are pushed to the main branch
